title: Tarek Allam
logo: /assets/img.png
#description: text below image
show_downloads: true
email: tarekallam.bme@gmail.com
name: Tarek Allam
description: >- # this means to ignore newlines until "keywords::"
  Test 
keywords: [Your keywords]
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
domain: "" # the domain name for your site, e.g. example.com
language: en

